version: '3'
services:
  loginserver:
    build: .
    ports:
      - 8080:8080
    networks:
      - loginbridgetest
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldbcompose:3306/dockerr
      - spring.datasource.username=usernames
      - spring.datasource.password=123456
      - spring.datasource.driver-class-name =com.mysql.cj.jdbc.Driver
    depends_on:
      - mysqldbcompose
  mysqldbcompose:
    image: mariadb:10.5.3
    ports:
      - '3307:3306'
    environment:
      MYSQL_DATABASE: 'dockerr'
      MYSQL_USER: 'usernames'
      MYSQL_PASSWORD: '123456'
      MYSQL_ROOT_PASSWORD: '123456'
    volumes:
      - /server/mysql:/var/lib/mysql
    networks:
      - loginbridgetest
networks:
 loginbridgetest:
#  external: true

      
      
      
      